import React, { Component } from 'react';
import moment from 'moment';
import './main.css';

class Wado extends Component {

    constructor(props) {
        super(props);
        this.state = { }
        this.timer = {};
    }

    componentDidMount() {
        this.timer=setInterval(() => {
            this.setState({
                currentTime: moment().format('hh:mm:ss a')
            })
        }, 1000);
    }

    componentWillUnmount() {
        clearInterval(this.timer);
    }
    
    render() {
        let { currentTime } = this.state;

        return (
            <div id="wado">
                <pre>
                    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNdmdyydmNMMMMMMoMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmdyysysyyyyssssyyhdmN.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmysydyyyyydhdyyyyshysso:hdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMyyyssyyyyyyssyyyyssyydhyoo+shMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMms+osooooo++oooossso++++yhhhsy/omMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh+++:----:--..-----::--.--/sdhhsohMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh++-.................-.....-:+ydsssdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd++`  `.----------------------:+shhsodMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo+- ``--::::---------------::::/oydmhsyMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+/.`.-----::::::----------:::::+oshmmhoNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMdo/-.--------:::------::::::::::/oshdmdyhMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMdy+-://+///:::////+ossysssso/::::+shmmmdyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMdds/ssyhhyys+++++osyyyysssoo+/:::/shmNmdysMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmy+osyyhhhyyso+++ossyyhhyso+/::::ohmdhyosMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmh++sysdmdhys/::/+ossoyyso++/:---/yhyso+oMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy:-:+osssso+-.-:::+oo++///:::----o+ss+/dMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs-.:+oooo++/..--:///////:::---..-::+o/sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd-.://+/+++-..-:/++///:::::::----::///NNNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/://///+++.----/+o+///::////:---:+++smmmNNNmNNNNNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNNNNNMNMMMM+:+++/+++/////++/+++////////:::::hdmNNMMMMNNNNmmmmNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMmhdmNMMMMMMNy/+++++++syssyyo//++/////////::+NMMMMMMMMMMNNNNNmmdNNMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNddddmNMMMMMMMMMNo//+++++ssyysso+//++////////:/hMMMMMMMMMMMNNNNmmdhhhhmmNNNmmmmmddh
MMMMMMMMMMMMMMMMMmydmNNMMMMMMMMMMMNo//+ooossoo+o+++o++//////////hhhyysssoo+++++++++++++oossyyyyyyyyy
MMMMMMMMMMMMMMMNmdmNNNMMMMMMMMMMMMMmo/+osssssoooo+++o+/////:..-:/+++ooossyyyyyyhhhhhhddddddddddddddd
MMMMMMMMMMMMMmdmmNNNNMMMMMMMMMMMMMMMmo/osoossssoo+//++++///`.+hhddddddddddddmddmmmmmmmmmmNNNNNNNNNNN
MMMMMMMMMMMmddmNNNNNNMMMMMMMMMMMMMMMMmssssssssso++++++o+++/:/mNNmmmmmmmdmNNNNNNNNNNNNNNmmmmmmmmmmmmm
MMMMMMMMMNddmmNNNNNNNNNNMMMMMMMMMMMMMMNhsysssyyysooo+++oooo/+NNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
MMMMMMMMNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMmhysssooo++oossyys+/+NNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
MMMMMMMNNNMMMNNMNNNNMMMMMMMMMMMMMMMMMNNMMMmdysooooosyysssso/+NMNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
MMMMMMMNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMNmNMMMMNmddhyyssooosyy/+NNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmm
MMMMMMMmmmNNNMMMMMMMMMMMMMMMMMMMMMMMMMmdNMMMMMMNdhsoooosdMh/+NNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmm
MMMMMMNmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMmdmMMMMMMMNNmdhyhNMMy/+NNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmm
MMMMMMmmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMNddmMMMMMMMMMMMMMMMMy/oNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmm
MMMMMNmmNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMNdddNMMMMMMMMMMMMMMMy/oNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmm
MMMMMmmNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMddhdMMMMMMMMMMMMMMMy/oMNNNNNNNNNNNNNNNNNNNNNNNNNmmmmNNmmmmmmN
MMMMMmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmdhhmMMMMMMMMMMMMMMs/oMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmNmmNN
MMMMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdhhhNMMMMMMMMMMMMMs/oMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhhhdMMMMMMMMMMMMN+/sMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdhhhmMMMMMMMMMMMd+/sMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhhhhNMMMMMMMMMNh+/sMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMNmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhhhdMMMMMMMMMdh+/yNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMNNNMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdhhdNMMMMMMMmo//+yNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhddmMMMMMMNy//++yNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMddddMMMMMMmyyh++hNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdddmMMMMNdddm++hMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmddmMMMMdhhmN++hNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
====================================================================================================
====================================================================================================
==================================== WHATS THE TIME MR WADDO? ======================================
====================================================================================================
====================================================================================================
====================================== THE TIME IS {currentTime} =====================================
====================================================================================================
====================================================================================================
                                                                                                                                                                                                                            
                </pre>
            </div>
        )
    }
}

export default Wado;
